# Generated by Django 4.1.7 on 2023-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='content',
            field=models.TextField(),
        ),
    ]
